### ISSUE TITLE
App crashes when no Lists for known words are available

### ISSUE THREAD

**Issue by johann-su** [HannHank/Vocablii#16]
When starting the App without having the List for known words in the Database the app crashes.
```
The method '[]' was called on null.
flutter: Receiver: null
flutter: Tried calling: []("Iknow")
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1      _Home.build.<anonymous closure> (package:Vocablii/home.dart:207:185)
```

**Comment by HannHank** [comment]
fixed, see commit.
